---
title: "About"
---

We are a group of Squamish residents connected over a common interest in machine learning, data science and AI. 

We aim to grow skills and knowledge, and make connections through a series of talks, group coding events, pair programming and hackathons.

We aim to provide a place for people to share knowledge in the domains of data science, machine learning and artificial intelligence. We try to structure our talks to be as participatory as possible - rather than just a lecture on a topic, we encourage input and material from our members, and encourage debate in the hope that this stimulates learning and growth of our members.

Take a look at our [vision statement](https://docs.google.com/document/d/1cQ-9EJJ3YpFvz5qRgnmhSTopMyAwF2qu9y8hHny2kJk/edit?usp=sharing)

To get involved, come along on Wednesday evenings to meet the group!

If you'd like to join our Slack messenger channel, or if you have any questions, you can shoot us an email here: [mlsquamish@gmail.com](mlsquamish@gmail.com)

We host our meets at [The Common](http://thecommon.io) - a community workspace on Cleveland. Check out their website and definitely give them a try if you have a remote job and want an office space. 

You can get 1/3 off your first 3 months of membership at The Common by obtaining a referral code from us. 

We also host at the [Easy Expense](https://www.easy-expense.com/) offices on 2nd Ave. They're a Squamish based company who made an app to automate your expense tracking. Check them out!

